/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DashboardLayout {
        "userName": string;
    }
    interface MyComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface NoData {
        "colSpan": number;
    }
    interface TableList {
        "colSpan": number;
        "list": string[];
        "userName": string;
    }
}
declare global {
    interface HTMLDashboardLayoutElement extends Components.DashboardLayout, HTMLStencilElement {
    }
    var HTMLDashboardLayoutElement: {
        prototype: HTMLDashboardLayoutElement;
        new (): HTMLDashboardLayoutElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNoDataElement extends Components.NoData, HTMLStencilElement {
    }
    var HTMLNoDataElement: {
        prototype: HTMLNoDataElement;
        new (): HTMLNoDataElement;
    };
    interface HTMLTableListElement extends Components.TableList, HTMLStencilElement {
    }
    var HTMLTableListElement: {
        prototype: HTMLTableListElement;
        new (): HTMLTableListElement;
    };
    interface HTMLElementTagNameMap {
        "dashboard-layout": HTMLDashboardLayoutElement;
        "my-component": HTMLMyComponentElement;
        "no-data": HTMLNoDataElement;
        "table-list": HTMLTableListElement;
    }
}
declare namespace LocalJSX {
    interface DashboardLayout {
        "userName"?: string;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface NoData {
        "colSpan"?: number;
    }
    interface TableList {
        "colSpan"?: number;
        "list"?: string[];
        "userName"?: string;
    }
    interface IntrinsicElements {
        "dashboard-layout": DashboardLayout;
        "my-component": MyComponent;
        "no-data": NoData;
        "table-list": TableList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dashboard-layout": LocalJSX.DashboardLayout & JSXBase.HTMLAttributes<HTMLDashboardLayoutElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "no-data": LocalJSX.NoData & JSXBase.HTMLAttributes<HTMLNoDataElement>;
            "table-list": LocalJSX.TableList & JSXBase.HTMLAttributes<HTMLTableListElement>;
        }
    }
}
